package kitty.testapp.inf.ds.right;

import java.util.Date;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import kitty.kaf.cache.CacheValueList;
import kitty.kaf.cache.LocalCacheCallback;
import kitty.kaf.cache.LocalCachedMap;
import kitty.kaf.exceptions.CoreException;
import kitty.kaf.io.KeyValue;
import kitty.kaf.listeners.ItemChangedEventListener;
import kitty.kaf.pools.jndi.JndiConnectionFactory;
import kitty.kaf.pools.jndi.Lookuper;
import kitty.kaf.pools.memcached.MemcachedClient;
import kitty.kaf.session.AbstractRequestSession;
import kitty.kaf.session.RequestSession;
import kitty.testapp.inf.ds.right.beans.Func;
import kitty.testapp.inf.ds.right.beans.FuncTreeNode;

public class FuncHelper {

    //[autogenerated:static(cached) statements=4]
    public static final MemcachedClient mc = MemcachedClient.newInstance(null, "default");

    static ItemChangedEventListener itemsChangedEventListener = new ItemChangedEventListener() {

        @Override
        public void change(Object sender) throws Throwable {
            localCacheChanged();
        }

        @Override
        public void remove(Object sender, Object item) throws Throwable {
            localCacheRemoved(item);
        }

        @Override
        public void edit(Object sender, Object item, Object newValue) throws Throwable {
            localCacheEdited(item, newValue);
        }

        @Override
        public void add(Object sender, Object item) throws Throwable {
            localCacheAdded(item);
        }
    };

    static LocalCacheCallback localCacheCallBack = new LocalCacheCallback() {

        @Override
        public CacheValueList<?, ?> onGetCacheValueList(Object source, long firstIndex, int maxResults, Date lastModified) throws Throwable {
            return FuncHelper.queryLatest(null, null, "default", firstIndex, maxResults, lastModified);
        }

        public boolean isNullId(Object v) {
            return ((Long) v).compareTo(-1L) <= 0;
        }
    };

    public static LocalCachedMap<Long, Func> localFuncMap = new LocalCachedMap<Long, Func>("func", mc, localCacheCallBack, itemsChangedEventListener, 10);

    static void localCacheChanged() throws Throwable {
    }

    static void localCacheRemoved(Object item) throws Throwable {
    }

    static void localCacheEdited(Object item, Object newValue) throws Throwable {
    }

    static void localCacheAdded(Object item) throws Throwable {
    }

    public static void delete(Object caller, Long loginUserId, List<Long> idList) throws Exception {
        //[autogenerated:return(delete) statements=2]
        FuncBeanRemote bean = JndiConnectionFactory.lookup("db", caller, Lookuper.JNDI_TYPE_EJB, "testappFuncBean", FuncBeanRemote.class);
        bean.delete(loginUserId, idList);
    }

    public static Func findById(Object caller, Long loginUserId, Long id) throws Exception {
        //[autogenerated:return(findById) statements=2]
        FuncBeanRemote bean = JndiConnectionFactory.lookup("db", caller, Lookuper.JNDI_TYPE_EJB, "testappFuncBean", FuncBeanRemote.class);
        return bean.findById(loginUserId, id);
    }

    public static Func findByUniqueKey(Object caller, Long loginUserId, String keyCode) throws Exception {
        //[autogenerated:return(findByUniqueKey) statements=2]
        FuncBeanRemote bean = JndiConnectionFactory.lookup("db", caller, Lookuper.JNDI_TYPE_EJB, "testappFuncBean", FuncBeanRemote.class);
        return bean.findByUniqueKey(loginUserId, keyCode);
    }

    public static Func insert(Object caller, Long loginUserId, Func o) throws Exception {
        //[autogenerated:return(insert) statements=2]
        FuncBeanRemote bean = JndiConnectionFactory.lookup("db", caller, Lookuper.JNDI_TYPE_EJB, "testappFuncBean", FuncBeanRemote.class);
        return bean.insert(loginUserId, o);
    }

    public static Func edit(Object caller, Long loginUserId, Func o) throws Exception {
        //[autogenerated:return(edit) statements=2]
        FuncBeanRemote bean = JndiConnectionFactory.lookup("db", caller, Lookuper.JNDI_TYPE_EJB, "testappFuncBean", FuncBeanRemote.class);
        return bean.edit(loginUserId, o);
    }

    public static List<Func> query(Object caller, Long loginUserId, String cmd, int maxResults, List<?> params) throws Exception {
        //[autogenerated:return(query) statements=2]
        FuncBeanRemote bean = JndiConnectionFactory.lookup("db", caller, Lookuper.JNDI_TYPE_EJB, "testappFuncBean", FuncBeanRemote.class);
        return bean.query(loginUserId, cmd, maxResults, params);
    }

    public static CacheValueList<?, ?> queryLatest(Object caller, Long loginUserId, String cmd, long firstIndex, int maxResults, Date lastModified) throws Exception {
        //[autogenerated:return(queryLatest) statements=2]
        FuncBeanRemote bean = JndiConnectionFactory.lookup("db", caller, Lookuper.JNDI_TYPE_EJB, "testappFuncBean", FuncBeanRemote.class);
        return bean.queryLatest(loginUserId, cmd, firstIndex, maxResults, lastModified);
    }

    public static KeyValue<Integer, List<Func>> queryPage(Object caller, Long loginUserId, String cmd, long firstIndex, int maxResults, List<?> params) throws Exception {
        //[autogenerated:return(queryPage) statements=2]
        FuncBeanRemote bean = JndiConnectionFactory.lookup("db", caller, Lookuper.JNDI_TYPE_EJB, "testappFuncBean", FuncBeanRemote.class);
        return bean.queryPage(loginUserId, cmd, firstIndex, maxResults, params);
    }

    public static Object execute(Object caller, Long loginUserId, String cmd, List<?> params) throws Exception {
        //[autogenerated:return(execute) statements=2]
        FuncBeanRemote bean = JndiConnectionFactory.lookup("db", caller, Lookuper.JNDI_TYPE_EJB, "testappFuncBean", FuncBeanRemote.class);
        return bean.execute(loginUserId, cmd, params);
    }

    public static void getCacheValueCompete(Func v) {
    }

    public static void insertOrEditPageProcess(HttpServletRequest request, HttpServletResponse response) {
        //[autogenerated:body(insertOrEditPageProcess) statements=4]
        String id = request.getParameter("id");
        String error = null;
        if (id != null) {
            try {
                RequestSession<?> session = AbstractRequestSession.getCurrentSession(request);
                Func p = FuncHelper.findById(null, session.getUser().getUserId(), Long.valueOf(id));
                if (p == null) error = "找不到功能信息[id=" + id + "]";
                else request.setAttribute("data", p);
            } catch (Throwable e) {
                error = e.getMessage();
            }
        }
        else request.setAttribute("data", new Func());
        if (error != null) request.setAttribute("error", error);
    }

    private static FuncTreeNode funcTreeNode = null;

    public static synchronized FuncTreeNode getFuncTreeNode() {
        try {
            if (funcTreeNode == null) {
                FuncTreeNode node = new FuncTreeNode();
                node.add(localFuncMap.getItems(), true);
                funcTreeNode = node;
            }
        } catch (Throwable e) {
            throw new CoreException(e);
        }
        return funcTreeNode;
    }
}
