package kitty.testapp.ejb.file;

import java.sql.SQLException;
import java.util.List;
import javax.ejb.Stateless;
import kitty.kaf.io.KeyValue;
import kitty.kaf.cache.CacheValueList;
import java.util.Date;
import kitty.kaf.dao.DaoBean;
import kitty.testapp.ejb.file.dao.FileHostDaoHelper;
import kitty.testapp.inf.ds.file.beans.FileHost;
import kitty.testapp.inf.ds.file.FileHostBeanRemote;

@Stateless(name = "testappFileHostBean", mappedName = "testappFileHostBean")
public class FileHostBean extends DaoBean implements FileHostBeanRemote {

    public void delete(Long loginUserId, List<Short> idList) throws SQLException {
        //[autogenerated:body(delete) statements=1]
        FileHostDaoHelper.delete(getDao(), loginUserId, idList);
    }

    public FileHost findById(Long loginUserId, Short id) throws SQLException {
        //[autogenerated:body(findById) statements=1]
        FileHost ret = FileHostDaoHelper.findById(getDao(), loginUserId, id);
        //[autogenerated:return(findById) statements=1]
        return ret;
    }

    public FileHost insert(Long loginUserId, FileHost o) throws SQLException {
        //[autogenerated:body(insert) statements=1]
        FileHost ret = FileHostDaoHelper.insert(getDao(), loginUserId, o);
        //[autogenerated:return(insert) statements=1]
        return ret;
    }

    public FileHost edit(Long loginUserId, FileHost o) throws SQLException {
        //[autogenerated:body(edit) statements=1]
        FileHost ret = FileHostDaoHelper.edit(getDao(), loginUserId, o);
        //[autogenerated:return(edit) statements=1]
        return ret;
    }

    public List<FileHost> query(Long loginUserId, String cmd, int maxResults, List<?> params) throws SQLException {
        //[autogenerated:body(query) statements=1]
        List<FileHost> ret = FileHostDaoHelper.query(getDao(), loginUserId, cmd, maxResults, params);
        //[autogenerated:return(query) statements=1]
        return ret;
    }

    public KeyValue<Integer, List<FileHost>> queryPage(Long loginUserId, String cmd, long firstIndex, int maxResults, List<?> params) throws SQLException {
        //[autogenerated:body(queryPage) statements=1]
        KeyValue<Integer, List<FileHost>> ret = FileHostDaoHelper.queryPage(getDao(), loginUserId, cmd, firstIndex, maxResults, params);
        //[autogenerated:return(queryPage) statements=1]
        return ret;
    }

    public CacheValueList<?, ?> queryLatest(Long loginUserId, String cmd, long firstIndex, int maxResults, Date lastModified) throws SQLException {
        //[autogenerated:body(queryLatest) statements=1]
        CacheValueList<?, ?> ret = FileHostDaoHelper.queryLatest(getDao(), loginUserId, cmd, firstIndex, maxResults, lastModified);
        //[autogenerated:return(queryLatest) statements=1]
        return ret;
    }

    public Object execute(Long loginUserId, String cmd, List<?> params) throws SQLException {
        //[autogenerated:body(execute) statements=1]
        Object ret = FileHostDaoHelper.execute(getDao(), loginUserId, cmd, params);
        //[autogenerated:return(execute) statements=1]
        return ret;
    }
}
