package kitty.testapp.inf.web;

import kitty.testapp.inf.enumdef.Gender;

/**
 * 
 * 自动生成的枚举类值
 * 
 */
public class EnumValues {

    public Gender[] getGenderList() {
        //[autogenerated:body(getGenderList) statements=1]
        return Gender.values();
    }
}
