package kitty.testapp.inf.web;

import java.util.List;
import kitty.testapp.inf.ds.file.FileCategoryHelper;
import kitty.testapp.inf.ds.file.FileHostHelper;
import kitty.testapp.inf.ds.right.FuncHelper;

/**
 * 
 * 自动生成的本地缓存值
 * 
 */
public class LocalCacheData {

    public List<?> getFileCategoryList() {
        //[autogenerated:body(gett_file_categoryList) statements=1]
        return FileCategoryHelper.localFileCategoryMap.getItems();
    }

    public List<?> getFileHostList() {
        //[autogenerated:body(gett_file_hostList) statements=1]
        return FileHostHelper.localFileHostMap.getItems();
    }

    public List<?> getFuncList() {
        //[autogenerated:body(gett_funcList) statements=1]
        return FuncHelper.localFuncMap.getItems();
    }
}
