package kitty.testapp.ejb.right.dao;

import java.sql.SQLException;
import kitty.kaf.dao.Dao;
import java.util.List;
import kitty.kaf.io.KeyValue;
import kitty.kaf.cache.CacheValueList;
import java.util.Date;
import kitty.testapp.inf.ds.right.beans.User;
import kitty.testapp.inf.ds.right.UserHelper;
import kitty.kaf.helper.SQLHelper;

public class UserDaoHelper {

    public static void delete(Dao dao, Long loginUserId, List<Long> idList) throws SQLException {
        //[autogenerated:body(deleteCheck) statements=1]
        if (idList != null && idList.size() > 0) {
            try {
                dao.beginUpdateDatabase();
                dao.execute(SQLHelper.buildDeleteOrListSql("t_user_role", "user_id", idList));
                dao.execute(SQLHelper.buildDeleteOrListSql("t_user_owner_role", "user_id", idList));
            } finally {
                dao.endUpdateDatabase();
            }
        }
        //[autogenerated:body(delete) statements=1]
        dao.delete(User.tableDef, idList);
        //[autogenerated:body(deleteAfter) statements=1]
        UserHelper.userMap.removeAll(idList);
    }

    public static User findById(Dao dao, Long loginUserId, Long id) throws SQLException {
        //[autogenerated:body(findById) statements=1]
        User ret = dao.findById(User.class, id);
        //[autogenerated:return(findById) statements=1]
        return ret;
    }

    public static User findByUniqueKey(Dao dao, Long loginUserId, String keyCode) throws SQLException {
        //[autogenerated:body(findByUniqueKey) statements=1]
        User ret = dao.findByUniqueKey(User.class, keyCode);
        //[autogenerated:return(findByUniqueKey) statements=1]
        return ret;
    }

    public static User insert(Dao dao, Long loginUserId, User o) throws SQLException {
        //[autogenerated:body(insert) statements=1]
        User ret = dao.insert(o);
        //[autogenerated:return(insert) statements=2]
        UserHelper.userMap.remove(o.getId());
        return ret;
    }

    public static User edit(Dao dao, Long loginUserId, User o) throws SQLException {
        //[autogenerated:body(edit) statements=1]
        User ret = dao.edit(o);
        //[autogenerated:return(edit) statements=2]
        UserHelper.userMap.remove(o.getId());
        return ret;
    }

    public static List<User> query(Dao dao, Long loginUserId, String cmd, int maxResults, List<?> params) throws SQLException {
        //[autogenerated:body(query) statements=2]
        List<User> ret = null;
        if (cmd.equalsIgnoreCase("default")) ret = dao.query(User.class, "from t_user a where a.is_delete=0", "", maxResults);
        //[autogenerated:return(query) statements=1]
        return ret;
    }

    public static KeyValue<Integer, List<User>> queryPage(Dao dao, Long loginUserId, String cmd, long firstIndex, int maxResults, List<?> params) throws SQLException {
        //[autogenerated:body(queryPage) statements=2]
        KeyValue<Integer, List<User>> ret = null;
        if (cmd.equalsIgnoreCase("default")) ret = dao.queryPage(User.class, "from t_user a where a.is_deleted=0", "", firstIndex, maxResults, params.get(0));
        //[autogenerated:return(queryPage) statements=1]
        return ret;
    }

    public static Object execute(Dao dao, Long loginUserId, String cmd, List<?> params) throws SQLException {
        //[autogenerated:body(execute) statements=1]
        Object ret = null;
        //[autogenerated:return(execute) statements=1]
        return ret;
    }

    public static CacheValueList<?, ?> queryLatest(Dao dao, Long loginUserId, String cmd, long firstIndex, int maxResults, Date lastModified) throws SQLException {
        //[autogenerated:body(queryLastest) statements=2]
        CacheValueList<?, ?> ret = null;
        if (cmd.equalsIgnoreCase("default")) ret = dao.queryLatest(User.class, "t_user a", "", "", firstIndex, maxResults, lastModified);
        //[autogenerated:return(queryLastest) statements=1]
        return ret;
    }
}
