package kitty.testapp.ejb.right;

import java.sql.SQLException;
import java.util.List;
import javax.ejb.Stateless;
import kitty.kaf.io.KeyValue;
import kitty.kaf.cache.CacheValueList;
import java.util.Date;
import kitty.kaf.dao.DaoBean;
import kitty.testapp.ejb.right.dao.FuncDaoHelper;
import kitty.testapp.inf.ds.right.beans.Func;
import kitty.testapp.inf.ds.right.FuncBeanRemote;

@Stateless(name = "testappFuncBean", mappedName = "testappFuncBean")
public class FuncBean extends DaoBean implements FuncBeanRemote {

    public void delete(Long loginUserId, List<Long> idList) throws SQLException {
        //[autogenerated:body(delete) statements=1]
        FuncDaoHelper.delete(getDao(), loginUserId, idList);
    }

    public Func findById(Long loginUserId, Long id) throws SQLException {
        //[autogenerated:body(findById) statements=1]
        Func ret = FuncDaoHelper.findById(getDao(), loginUserId, id);
        //[autogenerated:return(findById) statements=1]
        return ret;
    }

    public Func findByUniqueKey(Long loginUserId, String keyCode) throws SQLException {
        //[autogenerated:body(findByUniqueKey) statements=1]
        Func ret = FuncDaoHelper.findByUniqueKey(getDao(), loginUserId, keyCode);
        //[autogenerated:return(findByUniqueKey) statements=1]
        return ret;
    }

    public Func insert(Long loginUserId, Func o) throws SQLException {
        //[autogenerated:body(insert) statements=1]
        Func ret = FuncDaoHelper.insert(getDao(), loginUserId, o);
        //[autogenerated:return(insert) statements=1]
        return ret;
    }

    public Func edit(Long loginUserId, Func o) throws SQLException {
        //[autogenerated:body(edit) statements=1]
        Func ret = FuncDaoHelper.edit(getDao(), loginUserId, o);
        //[autogenerated:return(edit) statements=1]
        return ret;
    }

    public List<Func> query(Long loginUserId, String cmd, int maxResults, List<?> params) throws SQLException {
        //[autogenerated:body(query) statements=1]
        List<Func> ret = FuncDaoHelper.query(getDao(), loginUserId, cmd, maxResults, params);
        //[autogenerated:return(query) statements=1]
        return ret;
    }

    public KeyValue<Integer, List<Func>> queryPage(Long loginUserId, String cmd, long firstIndex, int maxResults, List<?> params) throws SQLException {
        //[autogenerated:body(queryPage) statements=1]
        KeyValue<Integer, List<Func>> ret = FuncDaoHelper.queryPage(getDao(), loginUserId, cmd, firstIndex, maxResults, params);
        //[autogenerated:return(queryPage) statements=1]
        return ret;
    }

    public CacheValueList<?, ?> queryLatest(Long loginUserId, String cmd, long firstIndex, int maxResults, Date lastModified) throws SQLException {
        //[autogenerated:body(queryLatest) statements=1]
        CacheValueList<?, ?> ret = FuncDaoHelper.queryLatest(getDao(), loginUserId, cmd, firstIndex, maxResults, lastModified);
        //[autogenerated:return(queryLatest) statements=1]
        return ret;
    }

    public Object execute(Long loginUserId, String cmd, List<?> params) throws SQLException {
        //[autogenerated:body(execute) statements=1]
        Object ret = FuncDaoHelper.execute(getDao(), loginUserId, cmd, params);
        //[autogenerated:return(execute) statements=1]
        return ret;
    }
}
