package kitty.testapp.ejb.right;

import java.sql.SQLException;
import java.util.List;
import javax.ejb.Stateless;
import kitty.kaf.io.KeyValue;
import kitty.kaf.cache.CacheValueList;
import java.util.Date;
import kitty.kaf.dao.DaoBean;
import kitty.testapp.ejb.right.dao.RoleDaoHelper;
import kitty.testapp.inf.ds.right.beans.Role;
import kitty.testapp.inf.ds.right.RoleBeanRemote;

@Stateless(name = "testappRoleBean", mappedName = "testappRoleBean")
public class RoleBean extends DaoBean implements RoleBeanRemote {

    public void delete(Long loginUserId, List<Integer> idList) throws SQLException {
        //[autogenerated:body(delete) statements=1]
        RoleDaoHelper.delete(getDao(), loginUserId, idList);
    }

    public Role findById(Long loginUserId, Integer id) throws SQLException {
        //[autogenerated:body(findById) statements=1]
        Role ret = RoleDaoHelper.findById(getDao(), loginUserId, id);
        //[autogenerated:return(findById) statements=1]
        return ret;
    }

    public Role insert(Long loginUserId, Role o) throws SQLException {
        //[autogenerated:body(insert) statements=1]
        Role ret = RoleDaoHelper.insert(getDao(), loginUserId, o);
        //[autogenerated:return(insert) statements=1]
        return ret;
    }

    public Role edit(Long loginUserId, Role o) throws SQLException {
        //[autogenerated:body(edit) statements=1]
        Role ret = RoleDaoHelper.edit(getDao(), loginUserId, o);
        //[autogenerated:return(edit) statements=1]
        return ret;
    }

    public List<Role> query(Long loginUserId, String cmd, int maxResults, List<?> params) throws SQLException {
        //[autogenerated:body(query) statements=1]
        List<Role> ret = RoleDaoHelper.query(getDao(), loginUserId, cmd, maxResults, params);
        //[autogenerated:return(query) statements=1]
        return ret;
    }

    public KeyValue<Integer, List<Role>> queryPage(Long loginUserId, String cmd, long firstIndex, int maxResults, List<?> params) throws SQLException {
        //[autogenerated:body(queryPage) statements=1]
        KeyValue<Integer, List<Role>> ret = RoleDaoHelper.queryPage(getDao(), loginUserId, cmd, firstIndex, maxResults, params);
        //[autogenerated:return(queryPage) statements=1]
        return ret;
    }

    public CacheValueList<?, ?> queryLatest(Long loginUserId, String cmd, long firstIndex, int maxResults, Date lastModified) throws SQLException {
        //[autogenerated:body(queryLatest) statements=1]
        CacheValueList<?, ?> ret = RoleDaoHelper.queryLatest(getDao(), loginUserId, cmd, firstIndex, maxResults, lastModified);
        //[autogenerated:return(queryLatest) statements=1]
        return ret;
    }

    public Object execute(Long loginUserId, String cmd, List<?> params) throws SQLException {
        //[autogenerated:body(execute) statements=1]
        Object ret = RoleDaoHelper.execute(getDao(), loginUserId, cmd, params);
        //[autogenerated:return(execute) statements=1]
        return ret;
    }
}
